apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodongo
          image: IMAGE_NAME
          ports:
            - containerPort: 3000